export const alert = {
  SHOW_ALERT_MESSAGE: 'SHOW_ALERT_MESSAGE',
  DISMISS_ALERT_MESSAGE: 'DISMISS_ALERT_MESSAGE'
}

export const authSession = {
  CHECKED_LOGIN_STATUS_SUCCESS: 'CHECKED_LOGIN_STATUS_SUCCESS',
  CHECKED_LOGOUT_STATUS_SUCCESS: 'CHECKED_LOGOUT_STATUS_SUCCESS',
  HIDDEN_WIDGETS_FOR_NEWSLETTER: 'HIDDEN_WIDGETS_FOR_NEWSLETTER',
  HIDDEN_WIDGETS_FOR_TOP_HERO: 'HIDDEN_WIDGETS_FOR_TOP_HERO',
  HIDDEN_WIDGETS_FOR_WELCOME: 'HIDDEN_WIDGETS_FOR_WELCOME'
}

export const common = {
  NAVIGATOR_FOR_DETAILED_RESTAURANT: 'NAVIGATOR_FOR_DETAILED_RESTAURANT',
  PAGE_LOADING_EFFECT_NORMAL: 'PAGE_LOADING_EFFECT_NORMAL',

  IMAGE_PLACEHOLDER_IMAGE: 'IMAGE_PLACEHOLDER_IMAGE',
  IMAGE_PLACEHOLDER_THUMBNAIL: 'IMAGE_PLACEHOLDER_THUMBNAIL',

  // PhotoBrowser type
  PHOTO_BROWSER_TYPE_FOR_POPUP: 'PHOTO_BROWSER_TYPE_FOR_POPUP',
  PHOTO_BROWSER_TYPE_FOR_SINGLE_PAGE: 'PHOTO_BROWSER_TYPE_FOR_SINGLE_PAGE',

  // Photos Terms parameters type
  PHOTOS_TERMS_PARAM_NORMAL: 'PHOTOS_TERMS_PARAM_NORMAL',
  PHOTOS_TERMS_PARAM_FOR_EDIT_RECIPE: 'PHOTOS_TERMS_PARAM_FOR_EDIT_RECIPE',
  PHOTOS_TERMS_PARAM_FOR_SLIDE_SHOW: 'PHOTOS_TERMS_PARAM_FOR_SLIDE_SHOW',
  // Users ordered in event
  PAGE_ORDERED_USERS_IN_EVENT: 'PAGE_ORDERED_USERS_IN_EVENT',
  // Review List Type
  RECIPES_LIST_FOR_RESTAURANT_PAGE: 'RECIPES_LIST_FOR_RESTAURANT_PAGE',
  RECIPES_LIST_FOR_EVENT_PAGE: 'RECIPES_LIST_FOR_EVENT_PAGE',
  RECIPES_LIST_FOR_LOGGED_USER_PAGE: 'RECIPES_LIST_FOR_LOGGED_USER_PAGE',
  // Photos Browser Type
  PHOTOS_BROWSER_PAGE_NORMAL: 'PHOTOS_BROWSER_PAGE_NORMAL',
  PHOTOS_BROWSER_PAGE_FOR_USER_PROFILE: 'PHOTOS_BROWSER_PAGE_FOR_USER_PROFILE',
  // Events List type
  EVENTS_LIST_FOR_RESTAURANT: 'EVENTS_LIST_FOR_RESTAURANT',
  EVENTS_LIST_FOR_USER: 'EVENTS_LIST_FOR_USER',
  // Upload Image
  UPLOAD_IMAGE_FILE_DROP: 'UPLOAD_IMAGE_FILE_DROP',
  UPLOAD_IMAGE_FILE_PREVIEW: 'UPLOAD_IMAGE_FILE_PREVIEW',
  // invoke parse cloud.
  CLOUD_STATISTIC_FOR_USER_STATE: 'CLOUD_STATISTIC_FOR_USER_STATE',
  CLOUD_STATISTIC_FOR_REVIEWS: 'CLOUD_STATISTIC_FOR_REVIEWS',
  CLOUD_RESTAURANT_ADDRESS: 'CLOUD_RESTAURANT_ADDRESS',
  CLOUD_INVITE_WITH_EMAILS: 'CLOUD_INVITE_WITH_EMAILS',
  // Google Address
  RESTAURANT_CLOUD_ADDRESS_MODEL: 'RESTAURANT_CLOUD_ADDRESS_MODEL',
  // Review sort tags
  REVIEW_SORT_NORMAL: 'REVIEW_SORT_NORMAL',
  REVIEW_SORT_NEWEST: 'REVIEW_SORT_NEWEST',
  REVIEW_SORT_OLDEST: 'REVIEW_SORT_OLDEST',
  REVIEW_SORT_HIGHEST: 'REVIEW_SORT_HIGHEST',
  REVIEW_SORT_LOWEST: 'REVIEW_SORT_LOWEST',

  // UserSingle Form Type
  // 1.1 LOGGED user left menus.
  LOGGED_USER_MENU_ABOUT: 'LOGGED_USER_MENU_ABOUT',
  LOGGED_USER_MENU_REVIEWS: 'LOGGED_USER_MENU_REVIEWS',
  LOGGED_USER_MENU_BROWSER_PHOTOS: 'LOGGED_USER_MENU_BROWSER_PHOTOS',
  LOGGED_USER_MENU_EVENTS: 'LOGGED_USER_MENU_EVENTS',
  LOGGED_USER_MENU_RECIPES: 'LOGGED_USER_MENU_RECIPES',
  // 1.2 Edit User.
  LOGGED_USER_EDIT_FORM: 'LOGGED_USER_EDIT_FORM',
  LOGGED_USER_INVITE_FORM: 'LOGGED_USER_INVITE_FORM',

  // Page form types
  PAGE_MAIN_FORM: 'PAGE_MAIN_FORM',
  PAGE_MAIN_FORM_WITH_PHOTO_OVERLAY: 'PAGE_MAIN_FORM_WITH_PHOTO_OVERLAY',
  PAGE_PHOTOS_BROWSER_FORM: 'PAGE_PHOTOS_BROWSER_FORM',
  PAGE_PHOTOS_BROWSER_FORM_WITH_PHOTO_OVERLAY: 'PAGE_PHOTOS_BROWSER_FORM_WITH_PHOTO_OVERLAY',
  PAGE_OVERLAY_SELECTED_PHOTO_FORM: 'PAGE_OVERLAY_SELECTED_PHOTO_FORM',
  PAGE_SINGLE_SELECTED_PHOTO_FORM: 'PAGE_SINGLE_SELECTED_PHOTO_FORM',
  PAGE_RECIPES_LIST_BROWSER_FORM: 'PAGE_RECIPES_LIST_BROWSER_FORM',

  // User Profile Type
  USERPROFILE_TYPE_UPVOTE: 'USERPROFILE_TYPE_UPVOTE',
  USERPROFILE_TYPE_DOWNVOTE: 'USERPROFILE_TYPE_DOWNVOTE',
  USERPROFILE_TYPE_SUBMITTED_POSTS: 'USERPROFILE_TYPE_SUBMITTED_POSTS',
  USERPROFILE_TYPE_FOLDER_LIST: 'USERPROFILE_TYPE_FOLDER_LIST',
  // IEAUserProfileAboutLayout Event Type
  USERPROFILE_RESET: 'USERPROFILE_RESET',
  USERPROFILE_LOADED: 'USERPROFILE_LOADED',

  // Users
  LOGGED_IN: 'LOGGED_IN',
  SET_SHARING: 'SET_SHARING',
  RESET_NUXES: 'RESET_NUXES',

  // Detailed Page(Restaurants,Events)
  OVERLAY_LOADED_MODEL_PAGE: 'OVERLAY_LOADED_MODEL_PAGE',
  OVERLAY_LOADED_MODEL_RESET: 'OVERLAY_LOADED_MODEL_RESET',
  STATISTIC_CLOUD_MODEL: 'STATISTIC_CLOUD_MODEL',
  EMAIL_SEND_CLOUD_MODEL: 'EMAIL_SEND_CLOUD_MODEL',
  SET_PLATFORM: 'SET_PLATFORM',
  SET_VERSION: 'SET_VERSION',
  LOGIN_VIA_SOCIAL: 'LOGIN_VIA_SOCIAL',
  ON_LOGIN_STATE_CHANGE: 'ON_LOGIN_STATE_CHANGE',
  ON_AUTH_FORM_FIELD_CHANGE: 'ON_AUTH_FORM_FIELD_CHANGE',
  REQUEST_API: 'REQUEST_API',
  RESET_ERROR: 'RESET_ERROR',
  SET_SESSION_TOKEN: 'SET_SESSION_TOKEN',
  DELETE_TOKEN_SUCCESS: 'DELETE_TOKEN_SUCCESS',
  GET_PROFILE_REQUEST: 'GET_PROFILE_REQUEST',
  GET_PROFILE_SUCCESS: 'GET_PROFILE_SUCCESS',
  GET_PROFILE_FAILURE: 'GET_PROFILE_FAILURE',
  ON_PROFILE_FORM_FIELD_CHANGE: 'ON_PROFILE_FORM_FIELD_CHANGE',
  PROFILE_UPDATE_REQUEST: 'PROFILE_UPDATE_REQUEST',
  PROFILE_UPDATE_SUCCESS: 'PROFILE_UPDATE_SUCCESS',
  PROFILE_UPDATE_FAILURE: 'PROFILE_UPDATE_FAILURE'
}

export const popup = {
  // App Overlay type
  OVERLAY_TYPE_MORE_TOPICS: 'OVERLAY_TYPE_MORE_TOPICS',
  OVERLAY_TYPE_LOGIN_UI: 'OVERLAY_TYPE_LOGIN_UI',
  OVERLAY_TYPE_LOGGED_USER_MENU: 'OVERLAY_TYPE_LOGGED_USER_MENU',
  OVERLAY_TYPE_ARTICLE_SAVE_BUTTON: 'OVERLAY_TYPE_ARTICLE_SAVE_BUTTON',
  OVERLAY_TYPE_SUBMIT_FLAG: 'OVERLAY_TYPE_SUBMIT_FLAG',
  OVERLAY_TYPE_MESSAGES_LIST: 'OVERLAY_TYPE_MESSAGES_LIST',
  OVERLAY_TYPE_USER_DELETE_CONFIRM: 'OVERLAY_TYPE_USER_DELETE_CONFIRM'
}

export const authAction = {
  // Sign up/ sign in form type
  LOGIN_PANEL_FORM_NORMAL: 'LOGIN_PANEL_FORM_NORMAL',
  LOGIN_PANEL_FORM_RESEND_VERIFICATION: 'LOGIN_PANEL_FORM_RESEND_VERIFICATION',
  SET_LOGIN_FORM_STATE_TYPE: 'SET_LOGIN_FORM_STATE_TYPE',
  // Social connection failure
  SOCIAL_CONNECTION_FAILURE_BUTTON_TYPE: 'SOCIAL_CONNECTION_FAILURE_BUTTON_TYPE',
  // Webbrowser Callback
  LOGIN_TWITTER_MOBILE_CALLBACK: 'LOGIN_TWITTER_MOBILE_CALLBACK',
  LOGIN_FACEBOOK_MOBILE_CALLBACK: 'LOGIN_FACEBOOK_MOBILE_CALLBACK'
}

// Login UI
export const login = {
  // Login UI
  LOGIN_FORM_TYPE_MAIN: 'LOGIN_FORM_TYPE_MAIN',
  LOGIN_FORM_TYPE_LOGIN: 'LOGIN_FORM_TYPE_LOGIN',
  LOGIN_FORM_TYPE_REGISTER: 'LOGIN_FORM_TYPE_REGISTER',
  LOGIN_FORM_TYPE_LOG_OUT: 'LOGIN_FORM_TYPE_LOG_OUT',
  LOGIN_FORM_TYPE_FORGOTPASSWORD: 'LOGIN_FORM_TYPE_FORGOTPASSWORD',
  LOGIN_FORM_TYPE_RESET_PASSWD: 'LOGIN_FORM_TYPE_RESET_PASSWD'
}

export const loginPage = {
  LOGIN_PAGE_IN_SINGLE: 'LOGIN_PAGE_IN_SINGLE',
  LOGIN_PAGE_IN_POPUP: 'LOGIN_PAGE_IN_POPUP'
}

export const loggedStatus = {
  PARSE_LOGGED_IN: 'PARSE_LOGGED_IN',
  PARSE_CONNECTED_DONE: 'PARSE_CONNECTED_DONE',
  PARSE_DISCONNECTED_DONE: 'PARSE_DISCONNECTED_DONE',
  PARSE_LOGGED_FAILURE: 'PARSE_LOGGED_FAILURE'
}

export const social = {
  // Social button type
  SOCIAL_BUTTON_FOR_LOGIN: 'SOCIAL_BUTTON_FOR_LOGIN',
  SOCIAL_BUTTON_FOR_CONNECTION: 'SOCIAL_BUTTON_FOR_CONNECTION',
  SOCIAL_BUTTON_TYPE_FACEBOOK: 'SOCIAL_BUTTON_TYPE_FACEBOOK',
  SOCIAL_BUTTON_TYPE_TWITTER: 'SOCIAL_BUTTON_TYPE_TWITTER'
}

export const userConnected = {
  // User connection type
  USER_CONNECT_VIA_NAME: 'USER_CONNECT_VIA_NAME',
  USER_CONNECT_VIA_FACEBOOK: 'USER_CONNECT_VIA_FACEBOOK',
  USER_CONNECT_VIA_TWITTER: 'USER_CONNECT_VIA_TWITTER'
}

export const authModel = {
  // For mobile
  SKIPPED_LOGIN: 'SKIPPED_LOGIN',
  LOGOUT: 'LOGOUT',
  SIGN_UP_DONE: 'SIGN_UP_DONE',
  PARSE_LOGIN_SUCCESS: 'PARSE_LOGIN_SUCCESS',
  PARSE_LOGIN_ALERT: 'PARSE_LOGIN_ALERT',
  ON_AUTH_FORM_FIELD_CHANGE: 'ON_AUTH_FORM_FIELD_CHANGE',
  // Request:
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  RESET_PASSWORD_REQUEST: 'RESET_PASSWORD_REQUEST',
  SIGNUP_REQUEST: 'SIGNUP_REQUEST',
  // After fetched, success/failure:
  DONE_RESET_PASSWORD_FAILURE: 'DONE_RESET_PASSWORD_FAILURE',
  DONE_RESET_PASSWORD_SUCCESS: 'DONE_RESET_PASSWORD_SUCCESS',
  // Login
  DONE_LOGIN_SUCCESS: 'DONE_LOGIN_SUCCESS',
  DONE_LOGIN_FAILURE: 'DONE_LOGIN_FAILURE',
  // Signup
  DONE_SIGNUP_SUCCESS: 'DONE_SIGNUP_SUCCESS',
  DONE_SIGNUP_FAILURE: 'DONE_SIGNUP_FAILURE',
  // Logout
  DONE_LOGOUT_SUCCESS: 'DONE_LOGOUT_SUCCESS',
  DONE_LOGOUT_FAILURE: 'DONE_LOGOUT_FAILURE',
  // Page Form type:
  PAGE_FORM_TYPE_LOGIN: 'PAGE_FORM_TYPE_LOGIN',
  PAGE_FORM_TYPE_FORGOT_PASSWORD: 'PAGE_FORM_TYPE_FORGOT_PASSWORD',
  PAGE_FORM_TYPE_REGISTER: 'PAGE_FORM_TYPE_REGISTER'
}

export const editModel = {
  // Model Form Mode
  MODEL_FORM_TYPE_NEW: 'MODEL_FORM_TYPE_NEW',
  MODEL_FORM_TYPE_EDIT: 'MODEL_FORM_TYPE_EDIT',

  // Edit Model
  EDIT_MODEL_TOGGLE_TYPE: 'EDIT_MODEL_TOGGLE_TYPE',
  ON_EDIT_MODEL_FORM_FIELD_CHANGE: 'ON_EDIT_MODEL_FORM_FIELD_CHANGE',
  ON_RESTAURANT_MODEL_FORM_ADDRESS_FIELD_CHANGE: 'ON_RESTAURANT_MODEL_FORM_ADDRESS_FIELD_CHANGE',
  ON_RESTAURANT_MODEL_FORM_ADDRESS_FIELD_SUCCESS: 'ON_RESTAURANT_MODEL_FORM_ADDRESS_FIELD_SUCCESS',

  // For submit Articles
  MODEL_FOR_SUBMIT_ARTICLES: 'MODEL_FOR_SUBMIT_ARTICLES',
  // Table edit type
  EDIT_TABLE_SINGLE_MODEL: 'EDIT_TABLE_SINGLE_MODEL',
  EDIT_TABLE_MULTIPLE_MODEL: 'EDIT_TABLE_MULTIPLE_MODEL',
  EDIT_TABLE_RESET: 'EDIT_TABLE_RESET'
}

export const cloud = {
  EMAIL_SEND_CLOUD_MODEL: 'EMAIL_SEND_CLOUD_MODEL'
}

export const alertType = {
  // Alert Type
  ALERT_TYPE_SUCCESS: 'ALERT_TYPE_SUCCESS',
  ALERT_TYPE_ERROR: 'ALERT_TYPE_ERROR',
  ALERT_TYPE_INFO: 'ALERT_TYPE_INFO'
}

// ===========================================================
// ===========================================================
//  *** Flags ***
// ===========================================================
// ===========================================================
export const flagState = {
  // Parse Object Model Status
  PARSE_OBJECT_FLAG_NORMAL: 'PARSE_OBJECT_FLAG_NORMAL',
  PARSE_OBJECT_FLAG_REMOVED: 'PARSE_OBJECT_FLAG_REMOVED'
}

// ===========================================================
// ===========================================================
//  *** Pages ***
// ===========================================================
// ===========================================================
export const pages = {
  // User single page type
  PAGE_USER_PROFILE_FOR_INFORMATION: 'PAGE_USER_PROFILE_FOR_INFORMATION',
  PAGE_USER_PROFILE_FOR_EDIT: 'PAGE_USER_PROFILE_FOR_EDIT',
  PAGE_USER_PROFILE_FOR_FOLDER_READ_LATER: 'PAGE_USER_PROFILE_FOR_FOLDER_READ_LATER',

  // User Profile left menus type
  USER_PROFILE_LEFT_SIDE_UPVOTE: 'USER_PROFILE_LEFT_SIDE_UPVOTE',
  USER_PROFILE_LEFT_SIDE_DOWNVOTE: 'USER_PROFILE_LEFT_SIDE_DOWNVOTE',
  USER_PROFILE_LEFT_SIDE_SUBMITTED_ARTICLES: 'USER_PROFILE_LEFT_SIDE_SUBMITTED_ARTICLES'
}

export const webBrowser = {
  BROWSER_FOR_READ_MORE: 'BROWSER_FOR_READ_MORE',
  BROWSER_FOR_LOGIN_TWITTER: 'BROWSER_FOR_LOGIN_TWITTER',
  BROWSER_FOR_LOGIN_FACEBOOK: 'BROWSER_FOR_LOGIN_FACEBOOK'
}

export const editModelAction = {
  SAVE_MODEL_REQUEST: 'SAVE_MODEL_REQUEST',
  ENABLE_MODEL_EVENT_ACTION: 'ENABLE_MODEL_EVENT_ACTION',
  UPDATE_MODEL_REQUEST: 'UPDATE_MODEL_REQUEST',
  UPDATE_MODEL_SUCCESS: 'UPDATE_MODEL_SUCCESS',
  UPDATE_MODEL_FAILURE: 'UPDATE_MODEL_FAILURE',
  UPDATE_MODEL_REQUEST_FOR_RECIPE_ID: 'UPDATE_MODEL_REQUEST_FOR_RECIPE_ID',
  UPDATE_MODEL_SUCCESS_FOR_RECIPE_ID: 'UPDATE_MODEL_SUCCESS_FOR_RECIPE_ID',
  UPDATE_MODEL_FAILURE_FOR_RECIPE_ID: 'UPDATE_MODEL_FAILURE_FOR_RECIPE_ID',
  WRITE_MODEL_DONE: 'WRITE_MODEL_DONE'
}
