export const realmQuery = {
  // Query Realm Objects List
  QUERY_PHOTOS_BY_TYPE: 'QUERY_PHOTOS_BY_TYPE',
  QUERY_NEAR_RESTAURANTS: 'QUERY_NEAR_RESTAURANTS',
  SEARCH_RESTAURANTS_PAGE: 'SEARCH_RESTAURANTS_PAGE',
  QUERY_EVENTS_FOR_RESTAURANT: 'QUERY_EVENTS_FOR_RESTAURANT',
  QUERY_PEOPLE_IN_EVENT: 'QUERY_PEOPLE_IN_EVENT',
  QUERY_USERS_FOR_EVENT: 'QUERY_USERS_FOR_EVENT',
  QUERY_RECIPES_FOR_USER: 'QUERY_RECIPES_FOR_USER',
  QUERY_SEARCH_USERS: 'QUERY_SEARCH_USERS',
  QUERY_SEARCH_RECIPES: 'QUERY_SEARCH_RECIPES',
  QUERY_REVIEWS: 'QUERY_REVIEWS'
}

export const model = {
  // Parse Object
  PARSE_CONFIGURE: 'PARSE_CONFIGURE',
  PARSE_RECORDS: 'PARSE_RECORDS',
  PARSE_RESTAURANTS: 'PARSE_RESTAURANTS',
  PARSE_EVENTS: 'PARSE_EVENTS',
  PARSE_PEOPLE_IN_EVENTS: 'PARSE_PEOPLE_IN_EVENTS',
  PARSE_USERS: 'PARSE_USERS',
  PARSE_PHOTOS: 'PARSE_PHOTOS',
  PARSE_RECIPES: 'PARSE_RECIPES',
  PARSE_REVIEWS: 'PARSE_REVIEWS'
}
