export const global = {
  APP_OVERLAY_SHOW_MODEL: 'APP_OVERLAY_SHOW_MODEL',
  APP_OVERLAY_DISMISS_MODEL: 'APP_OVERLAY_DISMISS_MODEL'
}

export const menuMore = {
  // Home More Menus
  MENU_ITEM_ADD_OR_EDIT_RESTAURANT: 'MENU_ITEM_ADD_OR_EDIT_RESTAURANT',
  MENU_ITEM_ADD_OR_EDIT_EVENT: 'MENU_ITEM_ADD_OR_EDIT_EVENT',
  MENU_ITEM_ADD_OR_EDIT_RECIPE: 'MENU_ITEM_ADD_OR_EDIT_RECIPE',
  MENU_ITEM_ADD_OR_EDIT_USER: 'MENU_ITEM_ADD_OR_EDIT_USER',
  MENU_ITEM_ADD_OR_EDIT_REVIEW: 'MENU_ITEM_ADD_OR_EDIT_REVIEW',
  MENU_ITEM_SEARCH_RESTAURANTS: 'MENU_ITEM_SEARCH_RESTAURANTS',
  MENU_ITEM_MANAGE_FRIENDS: 'MENU_ITEM_MANAGE_FRIENDS',
  MENU_ITEM_READ_REVIEWS: 'MENU_ITEM_READ_REVIEWS',
  MENU_ITEM_LOGGED_USER_INVITE: 'MENU_ITEM_LOGGED_USER_INVITE'
}

export const listSection = {
  // Search
  MENU_SECTIONS_SEARCH_RESTAURANTS: 'MENU_SECTIONS_SEARCH_RESTAURANTS',
  MENU_SECTIONS_SEARCH_FRIENDS: 'MENU_SECTIONS_SEARCH_FRIENDS',
  MENU_SECTIONS_SEARCH_REVIEWS: 'MENU_SECTIONS_SEARCH_REVIEWS',
  MENU_SECTIONS_SEARCH_RECIPES: 'MENU_SECTIONS_SEARCH_RECIPES',

  // Near Restaurants
  MENU_SECTIONS_NEAR_RESTAURANTS_EMPTY: 'MENU_SECTIONS_NEAR_RESTAURANTS_EMPTY',

  // Home menu items
  MENU_SECTIONS_MORE: 'MENU_SECTIONS_MORE',
  MENU_SECTIONS_NEAR_RESTAURANTS: 'MENU_SECTIONS_NEAR_RESTAURANTS',
  MENU_SECTIONS_EVENTS: 'MENU_SECTIONS_EVENTS',
  MENU_SECTIONS_PEOPLE_IN_EVENTS: 'MENU_SECTIONS_PEOPLE_IN_EVENTS',
  MENU_SECTIONS_ORDERED_RECIPES: 'MENU_SECTIONS_ORDERED_RECIPES',
  MENU_SECTIONS_DETAILED_RECIPE: 'MENU_SECTIONS_DETAILED_RECIPE',
  MENU_SECTIONS_REVIEWS: 'MENU_SECTIONS_REVIEWS',
  // Photos
  MENU_SECTIONS_PHOTOS: 'MENU_SECTIONS_PHOTOS',
  // Edit Form
  MENU_SECTIONS_EDIT_RESTAURANT_ADDRESS: 'MENU_SECTIONS_EDIT_RESTAURANT_ADDRESS'
}

export const headerButton = {
  // Rating Star List Header View
  HEADER_SVG_BUTTON_TAKE_PHOTO: 'HEADER_SVG_BUTTON_TAKE_PHOTO',
  HEADER_SVG_BUTTON_RECIPES_LIST: 'HEADER_SVG_BUTTON_RECIPES_LIST',
  HEADER_SVG_BUTTON_EDIT: 'HEADER_SVG_BUTTON_EDIT',
  HEADER_SVG_BUTTON_WRITE_REVIEW: 'HEADER_SVG_BUTTON_WRITE_REVIEW',
  HEADER_SVG_BUTTON_ADD_EVENT_FOR_RESTAURANT: 'HEADER_SVG_BUTTON_ADD_EVENT_FOR_RESTAURANT',
  HEADER_SVG_BUTTON_ADD_USER_FOR_EVENT: 'HEADER_SVG_BUTTON_ADD_USER_FOR_EVENT'
}

export const template = {
  // Email template type
  // userEmailTemplates:
  EMAILS_TEMPLATE_FOR_FORGOT_USER: 'EMAILS_TEMPLATE_FOR_FORGOT_USER',
  EMAILS_TEMPLATE_VERIFY_SIGN_UP_USER: 'EMAILS_TEMPLATE_VERIFY_SIGN_UP_USER',
  EMAILS_TEMPLATE_VERIFY_REMOVE_USER: 'EMAILS_TEMPLATE_VERIFY_REMOVE_USER',
  // articleEmailTemplates:
  EMAILS_TEMPLATE_ARTICLE_APPROVED: 'EMAILS_TEMPLATE_ARTICLE_APPROVED',
  EMAILS_TEMPLATE_ARTICLE_REJECTED: 'EMAILS_TEMPLATE_ARTICLE_REJECTED',
  // userProfileEmailTemplates:
  EMAILS_TEMPLATE_CONNECTED_VIA_FACEBOOK: 'EMAILS_TEMPLATE_CONNECTED_VIA_FACEBOOK',
  EMAILS_TEMPLATE_CONNECTED_VIA_TWITTER: 'EMAILS_TEMPLATE_CONNECTED_VIA_TWITTER',
  EMAILS_TEMPLATE_UPDATED_USER_DETAILS: 'EMAILS_TEMPLATE_UPDATED_USER_DETAILS',
  EMAILS_TEMPLATE_UPDATED_USER_EMAIL: 'EMAILS_TEMPLATE_UPDATED_USER_EMAIL'
}

export const fetch = {
  // PostHome, PostDaily
  LIST_VIEW_LOADED_BY_TYPE: 'LIST_VIEW_LOADED_BY_TYPE',
  LIST_VIEW_LOADED_BY_TYPE_FOR_DASH_TABLE: 'LIST_VIEW_LOADED_BY_TYPE_FOR_DASH_TABLE',
  LIST_VIEW_LOADED_FOR_TRENDING_TOPICS: 'LIST_VIEW_LOADED_FOR_TRENDING_TOPICS',
  LIST_VIEW_LOADED_EVENTS: 'LIST_VIEW_LOADED_EVENTS',
  LIST_VIEW_LOADED_ORDERED_USERS: 'LIST_VIEW_LOADED_ORDERED_USERS',
  LIST_VIEW_LOADED_RECIPES: 'LIST_VIEW_LOADED_RECIPES',
  LIST_VIEW_LOADED_USERS: 'LIST_VIEW_LOADED_USERS',
  LOADED_PHOTOS_BROWSER: 'LOADED_PHOTOS_BROWSER',
  LIST_ID_FOR_TRENDING_TOPICS: 'LIST_ID_FOR_TRENDING_TOPICS',
  LIST_VIEW_LOADED_FOR_PHOTOS_LIST: 'LIST_VIEW_LOADED_FOR_PHOTOS_LIST',
  LIST_VIEW_LOADED_FOR_ALL_USERS: 'LIST_VIEW_LOADED_FOR_ALL_USERS',
  LIST_VIEW_UPDATED_FOR_OWN_PHOTO: 'LIST_VIEW_UPDATED_FOR_OWN_PHOTO'
}

export const photosOverlay = {
  // Posts Overlay
  PUSH_PHOTOS_AS_SINGLE: 'PUSH_PHOTOS_AS_SINGLE',
  DISMISS_ALL_PHOTOS: 'DISMISS_ALL_PHOTOS',
  BACKWARD_ONE_PHOTOS: 'BACKWARD_ONE_PHOTOS',
  FORWARD_ONE_PHOTOS: 'FORWARD_ONE_PHOTOS'
}

export const paginationNavBar = {
  // Pagination Navigation Bar Type
  PAGINATION_NAVIGATION_BAR_FOR_NORMAL: 'PAGINATION_NAVIGATION_BAR_FOR_NORMAL',
  PAGINATION_NAVIGATION_BAR_FOR_RECIPES_IN_RESTAURANT:
    'PAGINATION_NAVIGATION_BAR_FOR_RECIPES_IN_RESTAURANT',
  PAGINATION_NAVIGATION_BAR_FOR_REVIEWS: 'PAGINATION_NAVIGATION_BAR_FOR_REVIEWS'
}

export const photoBrowserTitle = {
  // Photo browser title
  PHOTO_BROWSER_NORMAL_TITLE: 'PHOTO_BROWSER_NORMAL_TITLE',
  PHOTO_BROWSER_LOGGED_USER_TITLE: 'PHOTO_BROWSER_LOGGED_USER_TITLE',
  PHOTO_BROWSER_ORGANIZATION_RECIPE_TITLE: 'PHOTO_BROWSER_ORGANIZATION_RECIPE_TITLE'
}

export const offlineTask = {
  // async tasks
  SYNC_TASKS_BEGIN: 'SYNC_TASKS_BEGIN',
  SYNC_TASKS_END: 'SYNC_TASKS_END'
}

export const photoCache = {
  // Parse local Images folders
  PARSE_ORIGINAL_IMAGES: 'PARSE_ORIGINAL_IMAGES',
  PARSE_THUMBNAIL_IMAGES: 'PARSE_THUMBNAIL_IMAGES'
}

export const takePhotos = {
  // Take photos
  TAKEN_PHOTOS_LIST_RESET: 'TAKEN_PHOTOS_LIST_RESET',
  TAKEN_PHOTOS_LIST_ADD: 'TAKEN_PHOTOS_LIST_ADD',
  TAKEN_PHOTOS_LIST_SAVED: 'TAKEN_PHOTOS_LIST_SAVED'
}

export const photoBrowser = {
  // Photos Browser
  PHOTO_BROWSER_OPEN: 'PHOTO_BROWSER_OPEN',
  PHOTO_BROWSER_CLOSE: 'PHOTO_BROWSER_CLOSE',
  SECTION_PHOTOS_BROWSER_FOR_RESTAURANT: 'SECTION_PHOTOS_BROWSER_FOR_RESTAURANT',
  SECTION_PHOTOS_BROWSER_FOR_EVENT: 'SECTION_PHOTOS_BROWSER_FOR_EVENT',
  SECTION_PHOTOS_BROWSER_FOR_RECIPE: 'SECTION_PHOTOS_BROWSER_FOR_RECIPE',
  SECTION_PHOTOS_BROWSER_FOR_USER: 'SECTION_PHOTOS_BROWSER_FOR_USER'
}

export const editInput = {
  INPUT_DISPLAY_NAME: 'INPUT_DISPLAY_NAME',
  INPUT_EVENT_WHAT: 'INPUT_EVENT_WHAT',
  INPUT_RECIPE_PRICE: 'INPUT_RECIPE_PRICE',
  INPUT_REVIEW_BODY: 'INPUT_REVIEW_BODY'
}

export const input = {
  INPUT_USERNAME_OR_EMAIL: 'INPUT_USERNAME_OR_EMAIL',
  INPUT_USERNAME: 'INPUT_USERNAME',
  INPUT_EMAIL: 'INPUT_EMAIL',
  INPUT_PASSWORD: 'INPUT_PASSWORD',
  INPUT_NEW_PASSWORD: 'INPUT_NEW_PASSWORD'
}
