export const userStatistics = {
  STATUS_RECIPES: 'STATUS_RECIPES',
  STATUS_REVIEWS: 'STATUS_REVIEWS',
  STATUS_PHOTOS: 'STATUS_PHOTOS',
  STATUS_EVENTS: 'STATUS_EVENTS'
}

export const userStatisticsRows = {
  STATUS_ROWS_HEADER: 'STATUS_ROWS_HEADER',
  STATUS_ROWS_RIGHT: 'STATUS_ROWS_RIGHT',
  STATUS_ROWS_FOR_MOBILE: 'STATUS_ROWS_FOR_MOBILE'
}
