export const userMenu = {
  POPUP_ITEM_ABOUT_ME: 'POPUP_ITEM_ABOUT_ME',
  POPUP_ITEM_INVITE_FRIENDS: 'POPUP_ITEM_INVITE_FRIENDS',
  POPUP_ITEM_ACCOUNT_SETTINGS: 'POPUP_ITEM_ACCOUNT_SETTINGS',
  POPUP_ITEM_NEW_RESTAURANT: 'POPUP_ITEM_NEW_RESTAURANT'
}

export const afterFetch = {
  FETCH_HOOK_FOR_PHOTOS_LIST: 'FETCH_HOOK_FOR_PHOTOS_LIST',
  FETCH_HOOK_FOR_PHOTOS_IN_BROWSER: 'FETCH_HOOK_FOR_PHOTOS_IN_BROWSER',
  FETCH_HOOK_FOR_PHOTOS_IN_SINGLE_MODEL: 'FETCH_HOOK_FOR_PHOTOS_IN_SINGLE_MODEL'
}

export const rightButtons = {
  // Right Buttons Group Type
  RIGHT_BUTTON_GROUP_ADD_REVIEW: 'RIGHT_BUTTON_GROUP_ADD_REVIEW',
  RIGHT_BUTTON_GROUP_ADD_EVENT: 'RIGHT_BUTTON_GROUP_ADD_EVENT',
  RIGHT_BUTTON_GROUP_MANAGER_ORDERED_USERS: 'RIGHT_BUTTON_GROUP_MANAGER_ORDERED_USERS',
  RIGHT_BUTTON_GROUP_ADD_RECIPE: 'RIGHT_BUTTON_GROUP_ADD_RECIPE'
}

export const imageSideShow = {
  // Slide show type
  SLIDE_SHOW_VIEW_TYPE_NORMAL: 'SLIDE_SHOW_VIEW_TYPE_NORMAL',
  SLIDE_SHOW_VIEW_TYPE_USER_AVATOR: 'SLIDE_SHOW_VIEW_TYPE_USER_AVATOR',
  SLIDE_SHOW_VIEW_TYPE_LEFT_LIST_USER_AVATOR: 'SLIDE_SHOW_VIEW_TYPE_LEFT_LIST_USER_AVATOR',
  SLIDE_SHOW_VIEW_TYPE_PHOTOS_BROWSER: 'SLIDE_SHOW_VIEW_TYPE_PHOTO_BROWSER',
  SLIDE_SHOW_VIEW_TYPE_EDIT_USER: 'SLIDE_SHOW_VIEW_TYPE_EDIT_USER'
}

export const reviewListPage = {
  // Review List Type
  REVIEW_LIST_TYPE_NORMAL: 'REVIEW_LIST_TYPE_NORMAL',
  REVIEW_LIST_TYPE_USER_PROFILE_ABOUT: 'REVIEW_LIST_TYPE_USER_PROFILE_ABOUT',
  REVIEW_LIST_TYPE_USER_PROFILE_REVIEWS: 'REVIEW_LIST_TYPE_USER_PROFILE_REVIEWS'
}

export const pageStatisticType = {
  PAGE_WITH_STATISTIC_NORMAL: 'PAGE_WITH_STATISTIC_NORMAL',
  PAGE_WITH_STATISTIC_FOR_USER_PROFILE: 'PAGE_WITH_STATISTIC_FOR_USER_PROFILE'
}
