export const social = {
  // Social button type
  SOCIAL_BUTTON_FOR_LOGIN: 'SOCIAL_BUTTON_FOR_LOGIN',
  SOCIAL_BUTTON_FOR_CONNECTION: 'SOCIAL_BUTTON_FOR_CONNECTION',
  SOCIAL_BUTTON_TYPE_FACEBOOK: 'SOCIAL_BUTTON_TYPE_FACEBOOK',
  SOCIAL_BUTTON_TYPE_TWITTER: 'SOCIAL_BUTTON_TYPE_TWITTER'
}
