name: ieatta
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 12.1.4+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependency_overrides:
    # http: ^0.12.0
    # http_parser: ^4.0.0
    # intl: 0.17.0-nullsafety.2

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  font_awesome_flutter: ^9.1.0
  cached_network_image: ^3.1.0
  # permission
  permission_handler: ^8.1.4+2
  # local
  path_provider: ^2.0.2
  sqflite: ^2.0.0+3
  # image
  # https://github.com/r4jiv007/CloudinaryClient
  # cloudinary_client: ^0.0.9
  dio: ^4.0.0
  # https://github.com/Apparence-io/camera_awesome
  camerawesome: ^0.3.0+1
  image_picker: ^0.8.3+2
  # Nearby
  # https://pub.dev/packages/simple_connection_checker
  simple_connection_checker: ^0.2.1
  # https://github.com/DarshanGowda0/GeoFlutterFire
  rxdart: ^0.27.1
  # https://github.com/Lyokone/flutterlocation/tags
  location: ^4.3.0
  # i18
  # Localization https://github.com/dart-lang/intl
  # intl: ^0.17.0
  intl_utils: ^2.4.0
  flutter_localizations:
    sdk: flutter
  # database
  # Firebase(cloud_store,auth)
  # https://firebase.flutter.dev/docs/firestore/usage/
  cloud_firestore: ^2.5.0 # BoringSSL_GRPC(0.0.3)
  # https://firebase.flutter.dev/docs/auth/overview/
  firebase_auth: ^3.0.2
  # Third login
  google_sign_in: ^5.0.7
  # map
  google_maps_flutter: ^2.0.6
  # rxdart
  provider: ^6.0.0
  path: ^1.8.0
  shared_preferences: ^2.0.6
  # ui
  # https://github.com/cmdrootaccess/another-flushbar
  another_flushbar: ^1.10.24
  # https://github.com/danvick/flutter_form_builder
  flutter_form_builder: ^6.0.1 #6.0.0-nullsafety.1
  flutter_slidable: ^0.6.0
  # https://github.com/sarbagyastha/flutter_rating_bar
  # Icons.star_border | Icons.star
  # flutter_rating_bar: ^3.2.0+1
  flutter_spinkit: ^5.0.0
  # common
  slugify: ^2.0.0
  # timeAgo
  jiffy: ^4.1.0
  date_format: ^2.0.4
  # md5
  crypto: ^3.0.1
  # Exceptions
  # https://sentry.io/
  sentry_flutter: ^5.1.0
  # Annotations for Static Analysis
  meta: ^1.3.0
  # router
  # https://pub.dev/packages/fluro
  fluro: ^2.0.3
  # 获取当前设备信息 https://github.com/fluttercommunity/plus_plugins/tree/main/packages/device_info_plus
  device_info_plus: 2.1.0
  # Dart 常用工具类库 https://github.com/Sky24n/common_utils
  common_utils: 2.0.2
  # 启动URL的插件（支持Web） https://github.com/flutter/plugins/tree/master/packages/url_launcher
  url_launcher: 6.0.9
  # 处理键盘事件 https://github.com/diegoveloper/flutter_keyboard_actions
  keyboard_actions: ^3.4.3
  # Toast插件 https://github.com/OpenFlutter/flutter_oktoast
  oktoast: ^3.1.1
  # https://github.com/Sky24n/flustars
  flustars: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.1
  test: ^1.16.8

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/json/
    - assets/images/
    - assets/placeholder/
    - assets/stars/small/
    - assets/stars/large/
    - assets/graphics/
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/S    "_p_creator": "_User$ua04ebIMCn"
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 400

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_intl:
  enabled: true # Required. Must be set to true to activate the package. Default: false
  class_name: S # Optional. Sets the name for the generated localization class. Default: S
  main_locale: en # Optional. Sets the main locale used for generating localization files. Provided value should consist of language code and optional script and country codes separated with underscore (e.g. 'en', 'en_GB', 'zh_Hans', 'zh_Hans_CN'). Default: en
  arb_dir: lib/l10n 
  output_dir: lib/common/langs 
